In [0]:
import numpy as np

In [3]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [53]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1
arr3=arr1[0:,0:5:2]
arr3

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [54]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 
arr4=arr1[0::3,0::2]
arr4

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [46]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=100, size=10).reshape(2,5)
arr2

array([[51, 36, 85, 64, 98],
       [19, 24,  1, 19, 68]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [55]:
# Q3. Write a code to normalize arr2.
min1=min(arr2[0:1])
m=min(min1)
min2=min(arr2[1:2])
n=min(min2)
if m>n:
  c=n
else:
  c=m #finding minimum of arr2
max1=max(arr2[0:1])
m1=max(max1)
max2=max(arr2[1:2])
n1=min(max2)
if m1>n1:
  c1=m1
else:
  c1=n1 #finding maximum of arr2
c1,c



(98, 1)

In [48]:
value=(arr2-c)/(c1-c)
value #normalization achieved

array([[0.51546392, 0.36082474, 0.86597938, 0.64948454, 1.        ],
       [0.18556701, 0.2371134 , 0.        , 0.18556701, 0.69072165]])

In [49]:
value=(arr2-1)/(98-1)
value

array([[0.51546392, 0.36082474, 0.86597938, 0.64948454, 1.        ],
       [0.18556701, 0.2371134 , 0.        , 0.18556701, 0.69072165]])

In [50]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [52]:
# Q4. How would you check if your numpy array has some missing values?
np.isnan(arr2)
#by using isnan() function
# Hint: Thoda research karo numpy me existing functions hai

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [102]:
a=[10,18,14,12,16,1]
def twoarguments(a,n):
  n=int(input("enter the value of n to get the nth largest element  "))
  if(n>len(a)):
       print("out of range")
  else:
     a.sort()
     return a[len(a)-n]      
twoarguments(a,n)

enter the value of n to get the nth largest element  6


1